### PR TITLE
Fix/game state order, refactoring

### LINKED ISSUE #5: gameState logic order
change order of `gameState` blocks so that devs don't have to check if the gamestate is `playing` (since it comprises the majority of the program)

### PR DESCRIPTION
**Pull request by lavender-aa**
fixes #5
fixed the gamestate checking logic so that everything that should happen during `playing` does not need to be checked (but must be put after the `paused` block).
also refactored several things to declutter `update()`

### CODE REVIEW

**Comment by lavender-aa** [comment]
as a side note, this workflow seems a lot better to me, especially with the easy linking to issues and the fact that you don't need any special tools to locally checkout this PR (since it's just a branch).

File: source/main.lua [hunk 1]
```diff
@@ -285,147 +394,47 @@ function playdate.update ()
...
-            obstacleSprite:moveBy(baseGroundObstacleSpeed + addedGroundObstacleSpeed, 0)
-
-            -- if the obstacle is onscreen, render it
-            if obstacleSprite.x >= -7 and obstacleSprite.x <= 407 then
-                obstacleSprite:add()
-            -- otherwise, remove it
-            elseif obstacleSprite.x <= -7 then
-                obstacleSprite:remove()
-            end
+    gfx.drawText(score, 5, 5)
```
Comment (paulshriner) [inline source/main.lua]: If the player pauses or loses then this text won't be displayed. Since these 3 lines should always be displayed unless the player is at the title screen then you can just move then up higher in the function (before where line 381 currently is should work).

File: source/main.lua [hunk 2]
```diff
@@ -262,10 +363,18 @@ else
 end
 
 function playdate.update ()
+    -- refresh screen
+    gfx.sprite.update()
```
Comment (paulshriner) [inline source/main.lua]: Problem here is that this wipes out the lose text (you loser or new high score) as that is only displayed once in the addHighScore function. After the player loses there's no need to update the screen so this could just be wrapped in an if statement so it only runs when gameState ~= lost (though there might be a better way to do this).

**Review by paulshriner — CHANGES_REQUESTED** [review]
Overall looks good, I definitely think these changes will help with understanding the code in the future (and something I should consider more when writing the code). Just a couple minor issues which I added comments to.

File: source/main.lua (hunk 1 above)
Comment (lavender-aa) [reply source/main.lua]: should be fixed now

File: source/main.lua (hunk 2 above)
Comment (lavender-aa) [reply source/main.lua]: this solution seems simple enough and i can't think of anything else off the top of my head

**Review by paulshriner — APPROVED** [review]
This looks good now
